--general queries for getting all data from tables and count of users
SELECT * FROM HYPEDOCS_CO.PUBLIC.GOALS;
SELECT * FROM HYPEDOCS_CO.PUBLIC.HYPE_EVENTS;
SELECT COUNT(*) FROM HYPEDOCS_CO.PUBLIC.USERS;
SELECT * FROM HYPEDOCS_CO.PUBLIC.USERS;