--Counts of users with missions by membership status
SELECT DISTINCT COUNT(UID) FROM HYPEDOCS_CO.PUBLIC.USERS WHERE MISSION_TEXT is not NULL; --509
SELECT DISTINCT COUNT(UID) as BASIC_USER FROM HYPEDOCS_CO.PUBLIC.USERS WHERE MISSION_TEXT is not NULL AND STATUS='BASIC';
SELECT DISTINCT COUNT(UID) FROM HYPEDOCS_CO.PUBLIC.USERS WHERE MISSION_TEXT is not NULL AND STATUS = 'TRIAL_ENDED'; 
SELECT DISTINCT COUNT(UID) FROM HYPEDOCS_CO.PUBLIC.USERS WHERE MISSION_TEXT is not NULL AND STATUS = 'CANCELLED'; 